from pydantic_settings import BaseSettings
from dotenv import load_dotenv

load_dotenv()

class Settings(BaseSettings):
    OPENAI_API_KEY: str = ""
    SHOP_URL: str = ""
    FLASK_ENV: str = "development"
    SECRET_KEY: str = "change-me"
    DATABASE_URL: str = "sqlite:///data/app.db"

    LOCAL_LLM_BASE_URL: str = "http://localhost:1234/v1"
    LOCAL_LLM_MODEL: str = "Qwen2.5-VL-7B-Instruct"
    LOCAL_LLM_TIMEOUT: int = 90
    LOCAL_LLM_MAX_TOKENS: int = 700
    LOCAL_LLM_TEMPERATURE: float = 0.2
    LOCAL_LLM_MAX_RETRIES: int = 2

    IMAGE_EDITOR_PROVIDER: str = "comfyui"
    IMAGE_EDITOR_MODEL: str = "flux2-klein-4b"
    COMFYUI_BASE_URL: str = "http://127.0.0.1:8188"
    COMFYUI_TIMEOUT_SECONDS: int = 120
    COMFYUI_POLL_INTERVAL_SECONDS: float = 1.5

    IMAGE_MAX_INPUT_IMAGES: int = 4
    IMAGE_MAX_LONG_SIDE: int = 1024
    IMAGE_STORAGE_DIR: str = "data/images"
    IMAGE_DOWNLOAD_TIMEOUT_SECONDS: int = 20
    IMAGE_JPEG_QUALITY: int = 85

    class Config:
        env_file = ".env"

settings = Settings()

OPENAI_API_KEY = settings.OPENAI_API_KEY
SHOP_URL = settings.SHOP_URL
SECRET_KEY = settings.SECRET_KEY
DATABASE_URL = settings.DATABASE_URL
LOCAL_LLM_BASE_URL = settings.LOCAL_LLM_BASE_URL
LOCAL_LLM_MODEL = settings.LOCAL_LLM_MODEL
LOCAL_LLM_TIMEOUT = settings.LOCAL_LLM_TIMEOUT
LOCAL_LLM_MAX_TOKENS = settings.LOCAL_LLM_MAX_TOKENS
LOCAL_LLM_TEMPERATURE = settings.LOCAL_LLM_TEMPERATURE
LOCAL_LLM_MAX_RETRIES = settings.LOCAL_LLM_MAX_RETRIES

IMAGE_EDITOR_PROVIDER = settings.IMAGE_EDITOR_PROVIDER
IMAGE_EDITOR_MODEL = settings.IMAGE_EDITOR_MODEL
COMFYUI_BASE_URL = settings.COMFYUI_BASE_URL
COMFYUI_TIMEOUT_SECONDS = settings.COMFYUI_TIMEOUT_SECONDS
COMFYUI_POLL_INTERVAL_SECONDS = settings.COMFYUI_POLL_INTERVAL_SECONDS

IMAGE_MAX_INPUT_IMAGES = settings.IMAGE_MAX_INPUT_IMAGES
IMAGE_MAX_LONG_SIDE = settings.IMAGE_MAX_LONG_SIDE
IMAGE_STORAGE_DIR = settings.IMAGE_STORAGE_DIR
IMAGE_DOWNLOAD_TIMEOUT_SECONDS = settings.IMAGE_DOWNLOAD_TIMEOUT_SECONDS
IMAGE_JPEG_QUALITY = settings.IMAGE_JPEG_QUALITY
